[project]
name = "databits"
version = "0.1.0"
description = "This is really just to make it easier for an IDE w/ LSP"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "daft>=0.4.16",
    "polars>=1.30.0",
    "pyspark>=4.0.0",
]
